// <auto-generated />
using System;
using HeatconERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeatconERP.Infrastructure.Migrations
{
    [DbContext(typeof(HeatconDbContext))]
    partial class HeatconDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeatconERP.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BgClass")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EnquiryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeasibilityNotes")
                        .HasColumnType("text");

                    b.Property<string>("FeasibilityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gst")
                        .HasColumnType("text");

                    b.Property<bool>("IsAerospace")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRN", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorPurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorPurchaseOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorPurchaseInvoiceId");

                    b.HasIndex("VendorPurchaseOrderId");

                    b.ToTable("GRNs");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRNLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GRNId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GRNId");

                    b.HasIndex("MaterialVariantId");

                    b.ToTable("GRNLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.MaterialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MaterialCategories");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.MaterialVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialCategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinimumStockLevel")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("MaterialVariants");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SRSs");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRSBatchAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SRSLineItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StockBatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SRSLineItemId");

                    b.HasIndex("StockBatchId");

                    b.ToTable("SRSBatchAllocations");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRSLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequiredQuantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SRSId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialVariantId");

                    b.HasIndex("SRSId");

                    b.ToTable("SRSLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.StockBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GRNLineItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityAvailable")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GRNLineItemId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.HasIndex("MaterialVariantId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("StockBatches");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedSRSId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("StockBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkedSRSId");

                    b.HasIndex("LinkedWorkOrderId");

                    b.HasIndex("StockBatchId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactDetails")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GSTNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsApprovedVendor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorInvoiceQcDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorPurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorPurchaseInvoiceId", "CreatedAt");

                    b.ToTable("VendorInvoiceQcDecisions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorPurchaseOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorPurchaseOrderId");

                    b.HasIndex("VendorId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("VendorPurchaseInvoices");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorPurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialVariantId");

                    b.HasIndex("VendorPurchaseInvoiceId");

                    b.ToTable("VendorPurchaseInvoiceLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorPurchaseOrders");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorPurchaseOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialVariantId");

                    b.HasIndex("VendorPurchaseOrderId");

                    b.ToTable("VendorPurchaseOrderLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.WorkOrderMaterialRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequiredQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialVariantId");

                    b.ToTable("WorkOrderMaterialRequirements");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Ncr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("text");

                    b.Property<string>("ClosureNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disposition")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Ncrs");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PendingApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Originator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PendingApprovals");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseInvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseInvoiceLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPONumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PODate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuotationRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("QuotationRevisionId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseOrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EnquiryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ManualPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceBreakdown")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.QuotationLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.QuotationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("ChangeDetails")
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentToCustomerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentToCustomerBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("SnapshotAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SnapshotAttachments")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotClientName")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotDescription")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotLineItemsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("SnapshotManualPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SnapshotPriceBreakdown")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotProjectName")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotStatus")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationRevisions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssemblyCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedToUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MaterialCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PackingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PlanningCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProductionReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductionReceivedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("QcCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentToProductionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentToProductionBy")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TestingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WorkCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkCompletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WorkStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkStartedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderLineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderQualityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderQualityGateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderQualityGateId");

                    b.ToTable("WorkOrderQualityChecks");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderQualityGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedBy")
                        .HasColumnType("text");

                    b.Property<string>("GateStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassedBy")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "Stage")
                        .IsUnique();

                    b.ToTable("WorkOrderQualityGates");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRN", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", "VendorPurchaseInvoice")
                        .WithMany()
                        .HasForeignKey("VendorPurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", "VendorPurchaseOrder")
                        .WithMany("Grns")
                        .HasForeignKey("VendorPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VendorPurchaseInvoice");

                    b.Navigation("VendorPurchaseOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRNLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.GRN", "GRN")
                        .WithMany("LineItems")
                        .HasForeignKey("GRNId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany()
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GRN");

                    b.Navigation("MaterialVariant");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.MaterialVariant", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialCategory", "MaterialCategory")
                        .WithMany("Variants")
                        .HasForeignKey("MaterialCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRSBatchAllocation", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.SRSLineItem", "SRSLineItem")
                        .WithMany("BatchAllocations")
                        .HasForeignKey("SRSLineItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.StockBatch", "StockBatch")
                        .WithMany("SrsAllocations")
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SRSLineItem");

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRSLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany()
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.SRS", "SRS")
                        .WithMany("LineItems")
                        .HasForeignKey("SRSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialVariant");

                    b.Navigation("SRS");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.StockBatch", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.GRNLineItem", "GRNLineItem")
                        .WithOne("StockBatch")
                        .HasForeignKey("HeatconERP.Domain.Entities.Inventory.StockBatch", "GRNLineItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany("StockBatches")
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GRNLineItem");

                    b.Navigation("MaterialVariant");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.StockTransaction", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.SRS", "LinkedSRS")
                        .WithMany()
                        .HasForeignKey("LinkedSRSId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeatconERP.Domain.Entities.WorkOrder", "LinkedWorkOrder")
                        .WithMany()
                        .HasForeignKey("LinkedWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.StockBatch", "StockBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedSRS");

                    b.Navigation("LinkedWorkOrder");

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorInvoiceQcDecision", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", "VendorPurchaseInvoice")
                        .WithMany("QcDecisions")
                        .HasForeignKey("VendorPurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VendorPurchaseInvoice");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", "VendorPurchaseOrder")
                        .WithMany()
                        .HasForeignKey("VendorPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");

                    b.Navigation("VendorPurchaseOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoiceLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany()
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", "VendorPurchaseInvoice")
                        .WithMany("LineItems")
                        .HasForeignKey("VendorPurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialVariant");

                    b.Navigation("VendorPurchaseInvoice");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrderLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany()
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", "VendorPurchaseOrder")
                        .WithMany("LineItems")
                        .HasForeignKey("VendorPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialVariant");

                    b.Navigation("VendorPurchaseOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.WorkOrderMaterialRequirement", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Inventory.MaterialVariant", "MaterialVariant")
                        .WithMany()
                        .HasForeignKey("MaterialVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialVariant");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Ncr", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseInvoiceLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeatconERP.Domain.Entities.QuotationRevision", "QuotationRevision")
                        .WithMany()
                        .HasForeignKey("QuotationRevisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Quotation");

                    b.Navigation("QuotationRevision");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseOrderLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Enquiry", "Enquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryId");

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.QuotationLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Quotation", "Quotation")
                        .WithMany("LineItems")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.QuotationRevision", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.Quotation", "Quotation")
                        .WithMany("Revisions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany()
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderLineItem", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("LineItems")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderQualityCheck", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatconERP.Domain.Entities.WorkOrderQualityGate", "WorkOrderQualityGate")
                        .WithMany()
                        .HasForeignKey("WorkOrderQualityGateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderQualityGate");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrderQualityGate", b =>
                {
                    b.HasOne("HeatconERP.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRN", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.GRNLineItem", b =>
                {
                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.MaterialCategory", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.MaterialVariant", b =>
                {
                    b.Navigation("StockBatches");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRS", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.SRSLineItem", b =>
                {
                    b.Navigation("BatchAllocations");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.StockBatch", b =>
                {
                    b.Navigation("SrsAllocations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.Vendor", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseInvoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("QcDecisions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Inventory.VendorPurchaseOrder", b =>
                {
                    b.Navigation("Grns");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.Quotation", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("HeatconERP.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
